workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 13.3
      cocoapods: default
      groups:
        - remote_caching
      vars:
        XCODE_PROJECT: "UpcomingMovies.xcodeproj"
        XCODE_WORKSPACE: "UpcomingMovies.xcworkspace"
        XCODE_TARGET: "UpcomingMovies"
        XCODE_SCHEME: "UpcomingMovies"

    scripts:
      - name: Installing pods
        script: |
          pod install
      - name: Build IPA
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
