definitions:
 env_versions: &env_versions
   xcode: 13.3
 triggering:
  push: &push_event
      events:
        - push
 scripts:
    - &install
      name: Installing
      script: |
          pod install
          gem install rake && bundle install
    - &test 
      name: Run tests 
      script: | 
          xcode-project run-tests \
          --workspace UpcomingMovies.xcworkspace \
          --scheme UpcomingMovies \
          --device "iPhone 11"
workflows:
  ios-mac-pro-workflow:
    name: Mac Pro Workflow
    instance_type: mac_pro
    environment:
      <<: *env_versions
    triggering: 
      <<: *push_event
    scripts:
      - *install
      - *test
  ios-m1-rosetta-workflow:
    name: M1 Rosetta Workflow
    instance_type: mac_mini_m1
    environment:
      <<: *env_versions
    triggering: 
      <<: *push_event
    scripts:
      - *install
      - *test
